version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  version: 2
  test:
    jobs:
      - test_3_6
      - test_3_7
      - test_3_8
      - test_win
      - test_package

jobs:
  test_3_6: &test_template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: setup
          command: |
            set -e
            mkdir -p ~/test-reports
            mkdir -p ~/coredumps
            # install modern hg
            sudo pip3 install --disable-pip-version-check mercurial hg-evolve
            # configure hg
            echo -e "[ui]\nusername=mozphab test <moz-phab@example.com>" > ~/.hgrc
            echo -e "[extensions]\nevolve=" >> ~/.hgrc
            # configure git
            git config --global user.email "moz-phab-tests@example.com"
            git config --global user.name "moz-phab tests"
            # install test dependencies
            sudo pip3 install --disable-pip-version-check --requirement dev-requirements.txt
            sudo pip3 install --disable-pip-version-check --editable .
      - run:
          name: versions
          command: |
            set -e
            python3 --version
            git --version
            pip3 --disable-pip-version-check list --format freeze
      - run:
          name: run tests
          command: |
            set -e
            ulimit -c unlimited
            for F in tests/test_*.py; do
              pytest --junitxml=~/test-reports/junit-$( basename $F .py ).xml -vv $F
            done
            cp core.* ~/coredumps || true
      - store_test_results:
          path: ~/test-reports
      - store_artifacts:
          path: ~/test-reports
      - store_artifacts:
          path: ~/coredumps
  test_3_7:
    <<: *test_template
    docker:
      - image: circleci/python:3.7
  test_3_8:
    <<: *test_template
    docker:
      - image: circleci/python:3.8

  test_win:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install mercurial hg-evolve
            pip install --disable-pip-version-check --requirement dev-requirements.txt
            pip install --disable-pip-version-check --editable .
            git config --global user.email "moz-phab-tests@example.com"
            git config --global user.name "moz-phab tests"
      - run:
          name: versions
          command: |
            python --version
            git --version
            pip --disable-pip-version-check list --format freeze
      - run:
          name: run tests
          command: |
            mkdir test-reports
            function RunTest {
              & python -m pytest -vv @args
              if ($LASTEXITCODE -ne 0) {
                exit $LASTEXITCODE
              }
            }
            foreach ($f in Get-ChildItem -Path "tests" -Filter test_*.py) {
              RunTest --junitxml=test-reports/junit-$($f.BaseName).xml $f.FullName
            }
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  test_package:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: setup
          command: |
            python3 -m venv venv
            python3 setup.py sdist
            ./venv/bin/pip3 --disable-pip-version-check install dist/MozPhab*.tar.gz
      - run:
          name: run tests
          command: |
            ./venv/bin/pip3 --disable-pip-version-check show MozPhab
            ./venv/bin/moz-phab version
