version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            # venv
            virtualenv -p python2.7 venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            # modern hg
            pip install --upgrade mercurial hg-evolve
            # install arc, etc
            mkdir venv/arc
            git clone https://github.com/phacility/libphutil.git venv/arc/libphutil
            git clone https://github.com/phacility/arcanist.git venv/arc/arcanist
            ln -s $( pwd )/venv/arc/arcanist/bin/arc venv/bin/arc
            # configure git
            git config --global user.email "moz-phab-tests@example.com"
            git config --global user.name "moz-phab tests"
            # configure hg
            echo -e "[ui]\nusername=mozophab test <moz-phab@example.com>" > ~/.hgrc
            echo -e "[extensions]\nevolve=$( pwd )/venv/lib/python2.7/site-packages/hgext3rd/evolve" >> ~/.hgrc

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
