version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            # py2.7 & venv
            sudo apt-get install python2.7 python2.7-dev
            virtualenv -p python2.7 venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            # modern hg
            pip install --upgrade mercurial hg-evolve
            # configure git
            git config --global user.email "moz-phab-tests@example.com"
            git config --global user.name "moz-phab tests"
            # configure hg
            echo -e "[ui]\nusername=mozophab test <moz-phab@example.com>" > ~/.hgrc
            echo -e "[extensions]\nevolve=$( pwd )/venv/lib/python2.7/site-packages/hgext3rd/evolve" >> ~/.hgrc
            # linting tools
            pip install flake8
            sudo pip3 install black

      - run:
          name: linting
          command: |
            . venv/bin/activate
            black --check moz-phab *.py **/*.py
            flake8 --max-line-length=88 --ignore=E203,W503 --disable-noqa moz-phab *.py **/*.py

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
