version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            # py2.7 & modern hg
            sudo apt-get install python2.7 python2.7-dev python-pip
            sudo pip2 install --upgrade mercurial hg-evolve
            # configure hg
            echo -e "[ui]\nusername=mozphab test <moz-phab@example.com>" > ~/.hgrc
            echo -e "[extensions]\nevolve=" >> ~/.hgrc
            # configure git
            git config --global user.email "moz-phab-tests@example.com"
            git config --global user.name "moz-phab tests"
            # linting tools
            sudo pip install flake8 black
            # install test dependencies
            sudo pip install -r dev-requirements.txt

      - run:
          name: linting
          command: |
            black --check moz-phab *.py **/*.py
            flake8 --max-line-length=88 --ignore=E203,W503 --disable-noqa moz-phab *.py **/*.py

      - run:
          name: run tests
          command: |
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
